CREATE TABLE MEMBER (
MEMBER_EMAIL VARCHAR2(30) PRIMARY KEY,
MEMBER_PW VARCHAR2(20) NOT NULL,
MEMBER_NAME VARCHAR2(20) NOT NULL)




CREATE TABLE TOURIST_SPOT (
spot_pic VARCHAR2(200) NOT NULL,
SPOT_NAME VARCHAR2(50) PRIMARY KEY,
SPOT_REGION VARCHAR2(50) NOT NULL,
SPOT_ADDRESS VARCHAR2(100) NOT NULL,
SPOT_PHONENUMBER VARCHAR2(30) NOT NULL,
SPOT_PICTOGRAM_01 NUMBER NOT NULL,
SPOT_PICTOGRAM_02 NUMBER NOT NULL,
SPOT_PICTOGRAM_03 NUMBER NOT NULL,
SPOT_PICTOGRAM_04 NUMBER NOT NULL,
SPOT_PICTOGRAM_05 NUMBER NOT NULL,
SPOT_PICTOGRAM_06 NUMBER NOT NULL
SPOT_PICTOGRAM_07 NUMBER NOT NULL,
SPOT_PICTOGRAM_08 NUMBER NOT NULL,
SPOT_PICTOGRAM_09 NUMBER NOT NULL,
SPOT_PICTOGRAM_10 NUMBER NOT NULL,
SPOT_PICTOGRAM_11 NUMBER NOT NULL,
SPOT_PICTOGRAM_12 NUMBER NOT NULL)

insert into TOURIST_SPOT values('a','a','a','a','a',1,1,1,1,1,1,1,1,1,1,1,1)


CREATE TABLE REVIEW_BOARD (
REVIEW_NUM VARCHAR(15) PRIMARY KEY,
REVIEW_SPOT_NAME VARCHAR(50) NOT NULL,
REVIEW_TITLE VARCHAR2(200) NOT NULL,
REVIEW_CONTENTS VARCHAR2(500) NOT NULL,
REVIEW_MEMBER_EMAIL VARCHAR2(30) NOT NULL,
REVIEW_DATE DATE NOT NULL,
CONSTRAINT REVIEW_SPOT_NAME_FK FOREIGN KEY (REVIEW_SPOT_NAME) REFERENCES TOURIST_SPOT(SPOT_NAME),
CONSTRAINT REVIEW_MEMBER_EMAIL_FK FOREIGN KEY(REVIEW_MEMBER_EMAIL) REFERENCES MEMBER(MEMBER_EMAIL))

CREATE SEQUENCE SEQ_REVIEW_NUM


insert into member values('naver@abc.com','가나다','ㅁㅁㅁ')



CREATE TABLE FREE_BOARD (
FREE_NUM VARCHAR2(10) PRIMARY KEY,
FREE_TITLE VARCHAR(200) NOT NULL,
FREE_CONTENTS VARCHAR2(500) NOT NULL,
FREE_EMAIL VARCHAR2(30) NOT NULL,
FREE_PW VARCHAR2(30) NOT NULL,
FREE_DATE DATE NOT NULL)

CREATE SEQUENCE SEQ_FREE_NUM






CREATE TABLE SERVICE (
SERVICE_NAME VARCHAR2(50) PRIMARY KEY,
SERVICE_ADDRESS VARCHAR2(100) NOT NULL,
SERVICE_REGION VARCHAR2(50) NOT NULL,
SERVICE_PHONENUMBER VARCHAR2(30) NOT NULL,
SERVICE_TYPE VARCHAR2(50) NOT NULL)

INSERT INTO tourist_spot VALUES ('images_spot/test.jpg','죽녹원','전라남도','전라남도 담양군 서문대로 12','062-233-2009',1,0,1,0,0,0,0,0,0,0,1,1)











drop sequence SEQ_FREE_NUM;
drop table MEMBER;
SELECT * from REVIEW_BOARD;
SELECT * from tourist_spot
SELECT * from MEMBER
select * from FREE_BOARD;


truncate table review_board;
truncate table free_board;
truncate table question;






create table question (
	question_num VARCHAR2(20) primary key,
	question_name varchar2(100) not null,
	question_email varchar2(100) not null,
	question_text varchar2(500) not null,
	question_date DATE not null,
	question_answer varchar2(500)
)

drop table question [cascate constarints]

CREATE SEQUENCE SEQ_FREE_NUM
drop SEQUENCE SEQ_FREE_NUM
CREATE SEQUENCE SEQ_REVIEW_NUM
drop SEQUENCE SEQ_REVIEW_NUM

drop sequence seq_question


create sequence seq_question
insert into question values(seq_question.nextval, '성함' ,'email@naver.com', '안녕 메일테스트1' ,sysdate,'')

select * from question
